### ISSUE TITLE
input output data size not match

### ISSUE THREAD

**Issue by Minzhe** [PaccMann/TITAN#10]
Hi,

I'm using `flexible_model_eval.py` to predict my own input data, but the output prediction has fewer rows than input rows, and I don't know which rows are dropped. There should not be unfound receptor and ligand in the affinity file.

Part of reason may be set `drop_last=True` in `DataLoader`, but set to False still can't solve the problem completely. Could you help check the issue?

Thanks

**Comment by jannisborn** [comment]
Hi @Minzhe,
It's hard to debug from far, but definitely you have to set `drop_last=False` unless your sample size is a multiple of the batch size.
Have you done a `len` of the test dataset to see whether it's identical to the number of samples in your input file? If not, it means that some samples were discarded during dataset creation, most due to an incorrect data formatting

**Comment by jannisborn** [comment]
Please re-open if applicable
