### ISSUE TITLE
Need help with running semifrozen_finetuning.py

### ISSUE THREAD

**Issue by Lihua1990** [PaccMann/TITAN#5]
Hi,

I want to try your models and when I run the semifrozen_finetuning.py script using the data provided by you. I got the following error messages.

Maybe you can help solve it? Thanks a lot in advance.
![Screenshot 2022-03-29 162234](https://user-images.githubusercontent.com/29571453/160633957-8425ab79-ab2b-4b67-a8de-a2f0362a67c2.png)

Have a nice day!

Best,
Lihua

**Comment by paulrbuckley** [comment]
Hi,

I would like to report I am having the same issue, but by running the 'flexible_model_eval.py' script using provided data and suggested terminal arguments. I am wondering I am missing something?

Best,

Paul
[Cursor_and_TITAN-main_—_-bash_—_188×45.pdf](https://github.com/PaccMann/TITAN/files/8471476/Cursor_and_TITAN-main_._-bash_._188x45.pdf)

**Comment by jannisborn** [comment]
HI @paulrbuckley and @Lihua1990 
Thanks for your interest in our work and sorry for the late reply.

Did you verify that the path used at L140 (`model_dir/protein_language.pkl`) actually exists? If yes, my second guess is that it might be related to the python version you use 3.8 and 3.9 respectively and I think we developed the code on 3.7).

We will look more into this and come back soon

**Comment by paulrbuckley** [comment]
Thanks. Yes, i'm passing 'public/trained_model' as themodel path argument, and in that directory there is a file 'protein_language.pkl'

I'll try and see if I can get it working with python 3.7

**Comment by paulrbuckley** [comment]
To update, running in 3.7 appears to have resolved the issue. Still running the code but it hasn't immediately failed.

**Comment by Lihua1990** [comment]
Thanks for the reply. I have checked that the .pkl file is there. I will check later if this is the problem with the python version.

**Comment by Lihua1990** [comment]
> 

after downgrading python to 3.7, new error occurred 'No file exists' for 'best_ROC-AUC_bimodal_mca.pt', checked the directory inside the trained_model/weights/ one .pt file exists and I just renamed it. Now it is running, no error so far...

Thank you!

**Comment by jannisborn** [comment]
Hi,

I have slightly updated the workflow of the `semifrozen_finetuning.py` script to fix all your issues. Only minor changes were needed in the TITAN codebase itself

Original issue:
- [x] I released a new `pytoda` version which is the data handling package of `TITAN`. See release details for v1.0.1 [here](https://github.com/PaccMann/paccmann_datasets/releases/tag/v1.0.1) and v1.0.2 [here](https://github.com/PaccMann/paccmann_datasets/releases/tag/v1.0.2). The reason why you observed the `TypeError` when trying to restore the language object with `dill` is because we originally used python 3.7 to dump those objects. This is a known issue in `dill` and unrelated to the native pytoda code. There is currently an open PR in `dill` on this: https://github.com/uqfoundation/dill/pull/406

Followup issue:
- [x] I renamed the weights file from `done_training_bimodal_bimca.pt` to `best_ROC-AUC_bimodal_mca.pt` to avoid the last error @Lihua1990. Glad you fixed it yourself, but if you were to re-download the data from Box, it should work out of the  Box (pun intended!) now 

Housekeeping:
- [x] While doing this, I also fixed the argument name ordering/layout in the TITAN README
- [x] python version compatibility: I verified that the environment setup and the execution of the `semifrozen_finetuning.py` now runs smoothly with python 3.6, 3.7, 3.8 and 3.9
