### ISSUE TITLE
pytoda version is not correct

### ISSUE THREAD

**Issue by Minzhe** [PaccMann/TITAN#9]
Hi, I was trying to use TITAN to TCR epitope prediction by calling the `flexible_model_eval.py` script, my tcr and eiptope input are both `.csv` file. I got an error
![image](https://user-images.githubusercontent.com/10370142/171332296-49c494e0-419f-4ce0-ab3f-9c5f4a07b9fa.png)

I tried change `protein_language` to `protein_languages` in the `flexible_model_eval.py`, but got another error
![image](https://user-images.githubusercontent.com/10370142/171332486-3b77c938-467c-4a00-aacb-cc946d3a1dc6.png)

I install all the requirement listed in the `requirements.txt`,  but I doubt `pytoda==1.0.2` is the correct version to use the script.
Could you help check and test the code?

**Comment by jannisborn** [comment]
Hi @Minzhe, thanks for the interest in our work.
Indeed the script was written for `pytoda==0.2.4` so the easy solution is just to downgrade the package inside your env (you would need to install from source though since pytoda only ships via PyPI since 1.0.0) but you are totally right that the whole repo is in an unstable state now since only some of the scripts were migrated to pytoda 1.0.2

**Comment by annaweber209** [comment]
Hi @Minzhe, thanks for pointing out this issue! We did indeed forget to adapt the evaluation script to the new pytoda version. The newest commits should have fixed that!
